ns_distance_rest:
    pattern:  /rest/distance/{postalcode1}/{postalcode2}/{unit}
    defaults: { _controller: NSDistanceBundle:Rest:get, _format: json, unit: "k" }
    requirements:
        _method: GET
