services:
  ns_distance.postalcode_checker:
    class: NS\DistanceBundle\Services\PostalCodeChecker
    arguments: [ "@doctrine.orm.entity_manager" ]

  ns_distance.calculator:
    class: NS\DistanceBundle\Services\DistanceCalculator
    arguments: [ "@doctrine.orm.entity_manager" ]

