parameters:
#    ns_distance.example.class: NS\AuthBundle\Example

services:
    ns_distance.calculator:
      class: NS\DistanceBundle\Services\DistanceCalculator
      arguments: [ "@doctrine.orm.entity_manager" ]
