<?php

namespace NS\DistanceBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * PostalCode
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostalCode extends EntityRepository
{
    public function getByCodes(array $codes)
    {
        return $this->_em->createQuery("SELECT p FROM NS\DistanceBundle\Entity\PostalCode p INDEX BY p.postalCode WHERE p.postalCode IN (:ids)")
                  ->setParameters(array('ids'=>$codes))
                  ->getResult();
    }
}
