<?php

namespace NS\DistanceBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * PostalCode
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostalCode extends EntityRepository
{
    public function getByCodes($codes)
    {
        return $this->_em->createQuery("SELECT p FROM NS\DistanceBundle\Entity\PostalCode p INDEX BY p.postalCode WHERE p.postalCode IN (:p1,:p2)")
                  ->setParameters(array('p1'=>$codes[0],'p2'=>$codes[1]))
                  ->getResult();
    }
}
