<?php

namespace NS\DistanceBundle\Repositories;

use \Doctrine\ORM\EntityRepository;
use \Doctrine\ORM\UnexpectedResultException;

/**
 * PostalCode
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostalCode extends EntityRepository
{
    public function getByCodes(array $codes)
    {
        return $this->_em->createQuery("SELECT p 
                                        FROM NS\DistanceBundle\Entity\PostalCode p INDEX BY p.postalCode 
                                        WHERE p.postalCode IN (:ids)")
                  ->setParameters(array('ids'=>$codes))
                  ->getResult();
    }

    public function getByCode($postalCode)
    {
        try {
            return $this->createQueryBuilder('p')
                ->where('p.postalCode = :pCode')
                ->setParameter('pcode',$postalCode)
                ->getQuery()
                ->getSingleResult();
        } catch (UnexpectedResultException $exception) {
            return null;
        }
    }
}
