services:
  NS\DistanceBundle\Services\PostalCodeChecker:
    arguments: [ "@doctrine.orm.entity_manager", '%ns_distance.api_key%' ]

  ns_distance.postalcode_checker:
    alias: NS\DistanceBundle\Services\PostalCodeChecker

  NS\DistanceBundle\Services\DistanceCalculator:
    arguments: [ "@doctrine.orm.entity_manager" ]

  ns_distance.calculator:
    alias: NS\DistanceBundle\Services\DistanceCalculator
